apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.NetworkName}}
  namespace: {{.NetworkNamespace}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{.CniResourceName}}
spec:
  config: '{
  "cniVersion":"0.3.1",
  "name":"{{.NetworkName}}",
{{- if .MetaPluginsConfigured -}}
  "plugins": [
    {
{{- end -}}
  "type":"{{.CniType}}",
{{- if .CapabilitiesConfigured -}}
  "capabilities":{{.CniCapabilities}},
{{- end -}}
{{- if .Bridge -}}
  "bridge":"{{.Bridge}}",
{{- end -}}
{{- if .VlanTag -}}
  "vlan":{{.VlanTag}},
{{- end -}}
{{- if .MTU -}}
  "mtu":{{.MTU}},
{{- end -}}
{{- if .Trunk -}}
  "trunk":{{.Trunk}},
{{- end -}}
{{- if .OfportRequest -}}
  "ofport_request":{{.OfportRequest}},
{{- end -}}
{{- if .InterfaceType -}}
  "interface_type":"{{.InterfaceType}}",
{{- end -}}
{{- if .ConfigurationPath -}}
  "configuration_path":"{{.ConfigurationPath}}",
{{- end -}}
{{- if .SocketFile -}}
  "socket_file":"{{.SocketFile}}",
{{- end -}}
{{- if .LinkStateCheckRetries -}}
  "link_state_check_retries":{{.LinkStateCheckRetries}},
{{- end -}}
{{- if .LinkStateCheckInterval -}}
  "link_state_check_interval":{{.LinkStateCheckInterval}},
{{- end -}}
  {{.CniIpam}}
}
{{- if .MetaPluginsConfigured -}}
  ,
  {{.MetaPlugins}}
  ]
}
{{- end -}}
'
