contents: |
  [Unit]
  Description=Configures SRIOV NIC - post network stage
  After=systemd-networkd-wait-online.service NetworkManager-wait-online.service
  Before=network-online.target

  [Service]
  Type=oneshot
  ExecStart=/root/systemd-sandbox/sleep.sh post
  StandardOutput=journal+console

  [Install]
  WantedBy=network-online.target
enabled: true
name: sriov-config-post.service
