# permissions for end users to edit sriovnetworknodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworknodeconfig-editor-role
rules:
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodeconfigs/status
  verbs:
  - get
